title: JH coding
description: 
author: Joohyun Jo
github: https://github.com/tempJ
encoding: UTF-8
about: temphi20@gmail.com
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/tempJ"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Log
      url: /category/log

url: "https://tempj.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
